analyzer:
  exclude:
    - "**/*.dart"  # Excluye todos los archivos .dart
  errors:
    # Deshabilita todos los errores y warnings
    todo: ignore
    unused_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
    invalid_annotation_target: ignore

# Deshabilita todas las reglas del linter
linter:
  rules: {}